{% set name = "pynanoflann" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynanoflann-{{ version }}.tar.gz
  sha256: 72b64a3da0758f37e95969c283615c75c6d1df5f3d6a87ddba33ea2db0afeeed

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - scikit-build-core
    - pybind11 >=2.10
    - wheel
    - pip
    - nanoflann
  run:
    - python
    - numpy

test:
  imports:
    - pynanoflann
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/u1234x1234/pynanoflann
  summary: python wrapper for nanoflann
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
